---
- name: --Debian-- Update server
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: --Centos-- Update server
  yum:
    name: '*'
    state: latest
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: --Debian--  Install default packages
  apt:
    name:
      - vim
      - git
      - sshpass
      - openssh-client
      - openssh-server
      - htop
      - curl
      - wget
      - ca-certificates
      - apt-transport-https
      - software-properties-common
      - aptitude
      - python3-pip
      - python3-setuptools
    state: latest
  when: ansible_os_family == 'Debian'

- name: --Centos--  Install default packages
  dnf:
    name:
      - epel-release
      - vim
      - git
      - curl
      - wget
      - ca-certificates
      - python3-pip
      - python3-setuptools
      - yum-utils
      - bash-completion
    state: latest
  when: ansible_os_family == 'RedHat'

- name: Configure Timezone
  template:
    src: 'timezone.j2'
    dest: '/etc/timezone'
    mode: '0666'

- name: Clone repo infra
  git:
    repo: https://github.com/ckec/infra.git
    dest: /home/infra
    version: main
